load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "fileutil.go",
    ],
    importpath = "istio.io/core/auth/pkg/util",
    visibility = ["//visibility:public"],
)
