load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["platform.go"],
    importpath = "istio.io/core/pilot/platform",
    visibility = ["//visibility:public"],
)
